config/routes.rb
load Rails.root.join('lib', 'subdomains.rb')

Coursewareable::Engine.routes.draw do
  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  post 'signup' => 'users#create', :as => 'signup_post'
  post 'login' => 'sessions#create', :as => 'login_post'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :passwords, :only => [
    :new, :create, :update, :edit
  ]
  resources :users, :only => [:new, :create, :update] do
    get :activate, :on => :member
    collection do
      get :me
      get :my_account
      get :invite
      post :send_invitation
      get :notifications
      put :notifications, :to => :update_notifications
      get :request_deletion
      post :request_deletion
    end
  end

  constraints(Subdomains::Allowed) do
    get 'start' => 'classrooms#new', :as => 'start_classroom'
    post 'start' => 'classrooms#create', :as => 'start_classroom_post'

    resource(:home, :path => '/', :only => [:index] ) do
      get :dashboard
      post :feedback
      post :survey
    end
  end

  constraints(Subdomains::Forbidden) do
    resource(:classroom, :path => '/', :only => [:edit, :update] ) do
      collection do
        get :dashboard, :path => '/'
        post :announce
        get :staff
        get :stats
        resources(:memberships, :only => [:index, :create, :destroy])
        resources(:collaborations, :only => [:index, :create, :destroy])
        resource(:syllabus, :only => [:show, :edit, :update, :create])
        resources(:images, :only => [:index, :create, :destroy])
        resources(:uploads, :only => [:index, :create, :destroy])
        resources(:files, :only => [:index, :destroy])
        resources(:lectures, :except => [:index]) do
          resources(:assignments, :except => [:index]) do
            resources(:grades, :only => [
              :index, :new, :create, :destroy, :edit, :update])
            resources(:responses, :only => [:new, :create, :destroy, :show])
          end
        end
      end
    end
  end

  # Route to homepage by default
  root :to => 'homes#index'
end

Courseware::Application.routes.draw do
  # Route overwrites come below:

  # Mount the Coursewareable Engine
  mount Coursewareable::Engine => '/'
end

app/controllers/coursewareable/application_controller.rb
# The [Coursewareable] namespace
module Coursewareable
  # Courseware application controller
  class ApplicationController < ::ApplicationController
    # Ask users to authenticate
    before_filter :require_login

    # Handle errors
    rescue_from CanCan::AccessDenied, :with => :unauthorized
    rescue_from ActiveRecord::RecordNotFound, :with => :not_found

    private

    # Sorcery method overwritten to customize error message
    def not_authenticated
      args = {:subdomain => request.subdomain} unless request.subdomain.blank?
      redirect_to(login_url(args), :alert => _('Please authenticate first.'))
    end

    # Unauthorized error handler
    def unauthorized
      args = {:subdomain => request.subdomain} unless request.subdomain.blank?
      redirect_to(
        login_url(args), :alert => _('Access to this page is restricted.') )
    end

    # Not found handler
    def not_found
      redirect_to('/404')
    end

    # Redirect if authenticated
    def redirect_if_loggedin
      if logged_in?
        redirect_to(root_path, :alert => _('You logged in once already.'))
      end
    end
  end
end

app/controllers/coursewareable/assignments_controller.rb
module Coursewareable
  # Assignments controller
  class AssignmentsController < ApplicationController

    # Abilities checking for our nested resource
    load_and_authorize_resource :class => Coursewareable::Assignment
    skip_authorize_resource :only => [:create, :new]

    before_filter :load_classroom_lecture

    # Handles creation screen
    def new
      @assignment = @lecture.assignments.build
      @assignment.classroom = @classroom
      @assignment.user = current_user

      authorize!(:create, @assignment)
    end

    # Handles creation
    def create
      @assignment = @lecture.assignments.build(
        params[:assignment].except(:has_quiz))

      @assignment.classroom = @classroom
      @assignment.user = current_user

      authorize!(:create, @assignment)

      unless params[:has_quiz]
        @assignment.quiz = nil
      end

      if @assignment.save
        flash[:success] = _('Assignment was created.')
        redirect_to lecture_assignment_url(
          @lecture, @assignment, :subdomain => @classroom.slug)
      else
        flash[:alert] = _('There was an error, please try again.')
        render :new
      end
    end

    # Handles assignment screen
    def show
      @assignment = @lecture.assignments.find(params[:id])
    end

    # Handles editing screen
    def edit
      @assignment = @lecture.assignments.find(params[:id])
    end

    # Handles update
    def update
      @assignment = @lecture.assignments.find(params[:id])
      @assignment.update_attributes(params[:assignment])

      unless params[:has_quiz]
        @assignment.quiz = nil
      end

      if @assignment.save
        flash[:success] = _('Assignment was updated.')
        redirect_to lecture_assignment_url(
          @lecture, @assignment, :subdomain => @classroom.slug)
      else
        flash[:alert] = _('There was an error, please try again.')
        render :edit
      end

    end

    # Handles removal
    def destroy
      assignment = @lecture.assignments.find(params[:id])

      if assignment.destroy
        flash[:success] = _('Assignment removed.')
      end

      redirect_to lecture_path(@lecture)
    end

    protected

    # Loads current classroom and lecture
    def load_classroom_lecture
      @classroom = Coursewareable::Classroom.find_by_slug!(request.subdomain)
      @lecture = @classroom.lectures.find_by_slug(params[:lecture_id])
    end
  end
end

app/controllers/coursewareable/classrooms_controller.rb
module Coursewareable
  # Classroom controller
  class ClassroomsController < ApplicationController
    # Abilities checking
    load_and_authorize_resource :class => Coursewareable::Classroom
    skip_authorize_resource

    before_filter :load_classroom, :except => [:new, :create]
    before_filter :change_header_image, :only => [:update]

    # Classroom dashboard
    # Mapped to [Classroom] subdomain
    def dashboard
      authorize!(:dashboard, @classroom)
      timeline = @classroom.all_activities
      @timeline = Kaminari.paginate_array(timeline).page(params[:page])
      render(:partial => 'shared/timeline') if request.xhr?
    end

    # Classroom creation page
    def new
      @new_classroom = current_user.created_classrooms.build
      authorize!(:create, @new_classroom)
    end

    # Customization page
    def edit
      authorize!(:update, @classroom)
    end

    # Handles submitted changes
    def update
      authorize!(:update, @classroom)

      # Remove any built temporary image
      @classroom.images.reload

      attrs = params[:classroom].except(:color_scheme, :header_image, :color)
      @classroom.update_attributes(attrs)

      redirect_to dashboard_classroom_url(:subdomain => @classroom.reload.slug)
    end

    # Handles classroom creation
    def create
      classroom = current_user.created_classrooms.build(params[:classroom])
      authorize!(:create, classroom)

      if classroom.save
        redirect_to(root_url(:subdomain => classroom.slug))
      else
        flash[:alert] =
          _('Try another classroom title or fill in all the fields.')
        redirect_to(start_classroom_path)
      end
    end

    # Handles announcement creation
    def announce
      authorize!(:contribute, @classroom)

      activity_key = 'announcement.create'
      announcement = current_user.activities_as_owner.create(
        :key => activity_key, :recipient => @classroom, :parameters => {
          :content => Sanitize.clean(params[:announcement]),
          :user_name => current_user.name
        })
      ::AnnouncementMailer.delay.new_announcement_email(announcement)
      flash[:success] = _('Announcement was posted')
      redirect_to(dashboard_classroom_path)
    end

    # Handles staff page
    def staff
      authorize!(:dashboard, @classroom)
    end

    # Handles time-series stats page
    def stats
      authorize!(:dashboard, @classroom)

      respond_to do |format|
        format.html
        format.json {
          render :json => @classroom.all_activities.select([:created_at, :key])
        }
      end
    end

    protected

    # Loads current classroom
    def load_classroom
      @classroom = Coursewareable::Classroom.find_by_slug!(request.subdomain)
    end

    # Handle uploaded header image
    def change_header_image
      authorize!(:update, @classroom)

      himg = @classroom.images.build
      himg.attachment = params[:classroom][:header_image]
      himg.description = _('New header image')
      himg.assetable = @classroom
      himg.user = current_user
      return unless himg.valid?

      ok_size = Courseware.config.header_image_size
      # Wrap this in a rescue block to avoid all kind of weird exceptions
      begin
        size = Paperclip::Geometry.from_file(params[:classroom][:header_image])
      rescue
        return
      end

      return if size.width < ok_size[:width] or size.height != ok_size[:height]

      if can?(:create, himg) and himg.save
        @classroom.update_attribute(:header_image, himg.id)
      end
    end

  end
end

app/controllers/coursewareable/collaborations_controller.rb
module Coursewareable
  # Handles Classroom collaborations
  class CollaborationsController < ApplicationController
    # Abilities checking
    load_and_authorize_resource :class => Coursewareable::Collaboration
    skip_authorize_resource

    before_filter :load_classroom

    # Handles index listing screen
    def index
      authorize!(:update, @classroom)
    end

    # Handles creation
    def create
      authorize!(:update, @classroom)
      collaboration = @classroom.collaborations.build

      collab = Coursewareable::User.where(:email => params[:email]).first
      if collab.nil?
        invitation = current_user.sent_invitations.create(
          :email => params[:email], :classroom => @classroom,
          :role => Coursewareable::Collaboration.name)
        ::CollaborationMailer.delay.new_invitation_email(invitation)
        flash[:success] = _('An invitation was sent to %s.') % params[:email]
        redirect_to(collaborations_path) and return
      end

      collaboration.user = collab
      if can?(:create, collaboration) and collaboration.save
        flash[:success] = _('%s was added to collaborators') % collab.name
        ::CollaborationMailer.delay.new_collaboration_email(collaboration)
      end

      redirect_to(collaborations_path)
    end

    # Removes a collaborator
    def destroy
      collaboration = @classroom.collaborations.find(params[:id])
      authorize!(:destroy, collaboration)

      collaboration.destroy
      redirect_to collaborations_path
    end

    protected

    # Loads current classroom
    def load_classroom
      @classroom = Coursewareable::Classroom.find_by_slug!(request.subdomain)
    end
  end
end

app/controllers/coursewareable/files_controller.rb
module Coursewareable
  # Generic uploads handler
  class FilesController < ApplicationController

    # Abilities checking for our nested resource
    load_and_authorize_resource :class => Coursewareable::Asset
    skip_authorize_resource

    before_filter :load_classroom

    # All files listing page
    def index
      authorize!(:dashboard, @classroom)

      if can?(:contribute, @classroom)
        assets = @classroom.assets.reverse
      else
        assets = @classroom.assets.where(:user_id => current_user.id).reverse
      end

      @assets = Kaminari.paginate_array(assets).page(params[:page])
      render(:partial => 'listing') if request.xhr?
    end

    # Handles deletion of a file
    def destroy
      file = @classroom.assets.find(params[:id])
      authorize!(:destroy, file)

      if file and file.destroy
        flash.now[:success] = _('File was deleted')
        flash.keep
      end

      redirect_to files_path
    end

    protected

    # Loads current classroom
    def load_classroom
      @classroom = Coursewareable::Classroom.find_by_slug!(request.subdomain)
    end
  end
end

app/controllers/coursewareable/sessions_controller.rb
module Coursewareable
  # Courseware Sessions Controller
  class SessionsController < ApplicationController

    # Do not check for abilities
    skip_load_and_authorize_resource
    # Do not ask authentication
    skip_before_filter :require_login, :except => [:destroy]
    # Redirect if logged in
    before_filter :redirect_if_loggedin, :except => [:destroy]

    # New session screen handler
    def new
    end

    # New session handler
    def create
      user = login(params[:email], params[:password], params[:remember_me])
      subdomain = request.subdomain unless request.subdomain.blank? || false
      if user
        flash[:notice] = _('Welcome back %{name}!' % {:name => user.name})
        redirect_back_or_to(root_url(:subdomain => subdomain))
      else
        flash.now.alert = _('Email or password was invalid.')
        render :new
      end
    end

    # Destroys session, aka logout
    def destroy
      logout
      subdomain = request.subdomain unless request.subdomain.blank? || false
      redirect_to root_url(:subdomain => subdomain), :notice => _('Logged out!')
    end
  end
end

app/helpers/coursewareable/application_helper.rb
module Coursewareable
  # Courseware helpers
  module ApplicationHelper
    # Helper to set page title
    #
    # @param [String] page_title
    def title(page_title)
      content_for(:title, page_title) if page_title
    end

    # Helper to set embeds in HEAD
    #
    # @param [String] content
    def head_embed(content)
      content_for(:head_embed, content) if content
    end

    # Helper to set breadcrumbs content
    #
    # @param [String] content
    def breadcrumbs(content)
      content_for(:breadcrumbs, content) if content
    end

    # Helper to render the classroom header image
    # Defaults to a randomly provided image
    #
    # @return [String], generated style tag with CSS
    def header_image
      return if @classroom.nil? or @classroom.new_record?

      image = @classroom.images.find_by_id(@classroom.header_image)
      return if image.nil?

      @header_image = image.attachment.url
      render('shared/header_image')
    end

    # Generates a random header image from available list
    # Uses last classroom digit from it's ID
    #
    # @return [String], generated style tag with CSS
    def default_header_image
      return if @classroom.nil? or @classroom.new_record?

      image_id = @classroom.id % 10

      # Since we have only 1..7 available headers, lets map what doesn't fit
      image_id = 7 if image_id == 0 or image_id > 7
      @header_image = path_to_image("headers/#{image_id}.jpg")
      render('shared/header_image')
    end

    # Turns all http(s) URLs into HTML content if URL is an oembed link
    #
    # @param [String] text, the text to be checked for URLs
    # @return [String], the updated `text` with oembed content
    def auto_oembed(text)
      return ''.html_safe if text.blank?

      content = {}
      urls = URI.extract(text, %w(http https))

      return text.html_safe unless urls.count > 0

      urls.each do |url|
        html = fetch_and_render_oembed(url)
        content[url] = html unless html.blank?
      end

      content.each_pair do |key, value|
        text.sub!(key, value)
      end

      return text.html_safe
    end

    private

    # Tries to fetch `url` content from oembed providers
    # On success renders a partial from `shared/auto_oembed` based on
    # provider response type.
    #
    # @param [String] url, the URL to be checked
    # @return [String], the rendered partial content
    def fetch_and_render_oembed(url)
      begin
        response = OEmbed::Providers.get(url.to_str)
      rescue
        response = nil
      end

      render(
        :partial => "auto_oembed/#{response.type}",
        :locals => {:oembed => response}
      ) unless response.nil?
    end

  end
end

app/helpers/coursewareable/lectures_helper.rb
module Coursewareable
  # Courseware lectures controller helpers
  module LecturesHelper
    # Outputs a hierarchical structure of lectures based on its parent/children
    def list_lecture_options(lectures, selected=nil, listed_ids=[], indent='')
      return if lectures.nil?

      output = ''
      lectures.each do |lecture|
        unless listed_ids.include?(lecture.id)
          listed_ids.push(lecture.id)
          output += render(:partial => 'lecture_options', :locals => {
            :lecture => lecture, :listed_ids => listed_ids, :indent => indent,
            :selected => selected})
        end
      end
      return output.html_safe
    end
  end
end

app/helpers/coursewareable/syllabuses_helper.rb
module Coursewareable
  # Courseware syllabuses controller helpers
  module SyllabusesHelper
    # Outputs a hierarchical structure of lectures based on its parent/children
    def list_lectures_tree(lectures, listed_ids = [])
      output = ''
      lectures.each do |lecture|
        unless listed_ids.include?(lecture.id)
          listed_ids.push(lecture.id)
          output += render(:partial => 'lectures_listing', :locals => {
            :lecture => lecture, :listed_ids => listed_ids})
        end
      end
      return output.html_safe
    end
  end
end

app/views/coursewareable/assignments/_breadcrumbs.html.haml
.twelve.columns
  %ul.breadcrumbs
    %li
      = link_to(_('Syllabus'), syllabus_path)
    %li
      = link_to(@lecture.title, lecture_path(@lecture))
    %li.current
      %span
        = @assignment.title

app/views/coursewareable/assignments/_editor_breadcrumbs.html.haml
.twelve.columns
  %ul.breadcrumbs
    %li
      = link_to(_('Syllabus'), syllabus_path)
    %li
      = link_to(@lecture.title, lecture_path(@lecture))
    - unless @assignment.new_record?
      %li.current
        %span
          = _('Editing: %s') % @assignment.title
    - else
      %li.current
        %span
          = _('You are going to create a new assignment...')

app/views/coursewareable/assignments/_editor_sidebar.html.haml
.four.columns
  .row.sidebar
    %h5
      = _('About this assignment')
    %hr

    %p
      != _('You are about to add a new assignment to %s lecture.') % link_to(@lecture.title, lecture_path(@lecture))

    %p
      - assignments_count = pluralize(@lecture.assignments.count, _('assignment'), _('assignments'))
      - responses_count = pluralize(@lecture.responses.count, _('response'), _('responses'))
      - if @lecture.assignments.count > 1
        = _('There are already %s with %s for this lecture.') % [assignments_count, responses_count]
      - elsif @lecture.assignments.count == 1
        = _('There is already %s with %s for this lecture.') % [assignments_count, responses_count]
      - else
        = _('This would be the first assignment for this lecture.')

app/views/coursewareable/assignments/_quiz_builder_template.html.haml
%h5.marginless-top
  = _('Add questions')
%ul.button-group
  %li
    %a.quiz-new-text.tiny.button.simple.icon-plus{:href => "#"}
      = _('Single answer')
  %li
    %a.quiz-new-radios.tiny.button.simple.icon-plus{:href => "#"}
      = _('Multiple choices, one answer')
  %li
    %a.quiz-new-checkboxes.tiny.button.simple.icon-plus{:href => "#"}
      = _('Multiple choices, multiple answers')

.quiz-text.template.question.row{:style => "display: none"}
  .twelve.columns.question-content
    %textarea.input{:placeholder => _('Question content...')}
    .row.option
      .eleven.offset-by-one.columns.option-content
        %textarea{:placeholder => _('Possible answer content...')}
  .row
    .twelve.columns.align-right
      %a.alert.delete.icon-remove.smaller{:href => "#"}
        = _('Remove entire question')

.quiz-radios.template.question.row{:style => "display: none"}
  .twelve.columns.question-content
    %textarea.input{:placeholder => _('Question content...')}
    .row.option
      .one.columns.option-validation.align-center
        %input{:name => "unique", :type => "radio"}
        %p.padded-top-ten
          %a.alert.remove.icon-remove{:href => "#", :title => _('Remove this option')}
            -# = _('Remove option')
      .eleven.columns.option-content
        %textarea{:placeholder => _('Possible answer content...')}
  .row
    .six.columns
      %a.add.icon-plus{:href => "#"}
        = _('Add another choice')
    .six.columns.align-right
      %a.alert.delete.icon-remove.smaller{:href => "#"}
        = _('Remove entire question')

.quiz-checkboxes.template.question.row{:style => "display: none"}
  .twelve.columns.question-content
    %textarea.input{:placeholder => _('Question content...')}
    .row.option
      .one.columns.option-validation.align-center
        %input{:type => "checkbox"}
        %p.padded-top-ten
          %a.alert.remove.icon-remove{:href => "#", :title => _('Remove this choice')}
            -# = _('Remove choice')
      .eleven.columns.option-content
        %textarea{:placeholder => _('Possible answer content...')}
  .row
    .six.columns
      %a.add.icon-plus{:href => "#"}
        = _('Add another choice')
    .six.columns.align-right
      %a.alert.delete.icon-remove.smaller{:href => "#"}
        = _('Remove entire question')

app/views/coursewareable/assignments/_quiz_checkboxes.html.haml
.quiz-checkboxes.question.row
  .twelve.columns.question-content
    .panel
      = auto_oembed(question['content']).html_safe

    - question['options'].each_with_index do |answer, index|
      .row.option
        .one.columns.option-validation.align-center
          %input{:name => "unique", :type => "checkbox", :disabled => true, :checked => answer['valid']}
        .eleven.columns.option-content
          %textarea{:disabled => true}
            = answer['content']

app/views/coursewareable/assignments/_quiz_radios.html.haml
.quiz-radios.question.row
  .twelve.columns.question-content
    .panel
      = auto_oembed(question['content']).html_safe

    - question['options'].each_with_index do |answer, index|
      .row.option
        .one.columns.option-validation.align-center
          %input{:name => "unique", :type => "radio", :disabled => true, :checked => answer['valid']}
        .eleven.columns.option-content
          %textarea{:disabled => true}
            = answer['content']

app/views/coursewareable/assignments/_quiz_text.html.haml
.quiz-text.question.row
  .twelve.columns.question-content
    .panel
      = auto_oembed(question['content']).html_safe

    .row.option
      .eleven.offset-by-one.columns.option-content
        %textarea{:disabled => true}
          = question['options'].first['content']

app/views/coursewareable/assignments/_sidebar_collaborator.html.haml
%h5
  = link_to(_(''), edit_lecture_assignment_path(@lecture, @assignment), :class => 'icon-edit right', :id => 'assignment-update')
  = _('About this assignment')
%hr

%p.smaller
  = _('Last time updated by %s on %s.') % [@assignment.user.name, @assignment.updated_at.to_s(:pretty)]
  = link_to(_('You can update this assignment'), edit_lecture_assignment_path(@lecture, @assignment))

%p
  != _('This assignment relates to %s lecture.') % link_to(@lecture.title, lecture_path(@lecture))

%p.icon-docs
  - assignments_count = pluralize(@lecture.assignments.count, _('more assignment'), _('more assignments'))
  - responses_count = pluralize(@lecture.responses.count, _('response'), _('more responses'))
  - if @lecture.assignments.count > 1
    = _('There are %s and %s for this lecture.') % [assignments_count, responses_count]
  - elsif @lecture.assignments.count == 1
    = _('There is %s and %s for this lecture.') % [assignments_count, responses_count]
  - else
    = _('This is the first assignment for this lecture.')

%p.icon-hammer
  != _('You can also %s for this assignment.') % link_to(_('update the grades'), lecture_assignment_grades_path(@lecture, @assignment))


%h5
  = pluralize(@assignment.responses.count, _('assignment response'), _('assignment responses'))
%hr
- if @assignment.responses.empty?
  %p
    = _('There are no responses to evaluate.')
- else
  %ul.itemized.responses-listing
    - @assignment.responses.each do |response|
      %li
        = link_to(_('%s response') % response.user.name, lecture_assignment_response_path(@lecture, @assignment, response))

%h5
  = pluralize(@assignment.grades.count, _('assignment grade'), _('assignment grades'))
%hr

- if @assignment.grades.empty?
  %p
    != _('There are no grades for this assignment, but you can %s now.') % link_to(_('add a grade'), lecture_assignment_grades_path(@lecture, @assignment))
- else
  %ul.itemized.grades-listing
    %li
      %strong
        = link_to(_('Grade someone else'), new_lecture_assignment_grade_path(@lecture, @assignment))
    - @assignment.grades.limit(3).each do |grade|
      %li
        - grade_for = _('Grade for %s') % grade.receiver.name
        = link_to(grade_for, edit_lecture_assignment_grade_path(@lecture, @assignment, grade))
    - if @assignment.grades.count > 3
      %li.smaller.align-right
        != _('Including %s...') % link_to(_('%d more grades') % @assignment.grades.offset(3).count, lecture_assignment_grades_path(@lecture, @assignment))

app/views/coursewareable/assignments/edit.html.haml
= title _('Editing assignment')
= head_embed javascript_include_tag('edit_assignment')
= head_embed javascript_include_tag('editor')
= head_embed stylesheet_link_tag('editor')
= breadcrumbs(render('editor_breadcrumbs'))

#assignment
  .eight.columns

    = form_for(@assignment, :url => lecture_assignment_path(@lecture, @assignment)) do |f|
      %p
        = f.label :title, _('Title')
        = f.text_field :title, :required => true

      %p
        = f.label :content, _('Content')
        = f.text_area :content, :class => 'wysiwyg-full', :required => true

      %p
        - expanded_class = (@assignment.quiz.blank? ? '' : 'expanded')
        = check_box_tag :has_quiz, nil, (@assignment.quiz.blank? ? false : true), :class => ['expands left marginless-top', expanded_class], 'data-expand-target' => '.quiz-builder', 'data-look-allover' => 'true', 'data-toggle-class' => 'expanded'
        = label_tag :has_quiz, _('Add a quiz to this assignment')

      .hide.quiz-builder{'data-quiz' => :auto, 'data-from-store' => :true}
        = f.hidden_field :quiz, :value => @assignment.quiz.to_json, :class => 'quiz-store'
        = render(:partial => 'quiz_builder_template')

      %p
        = hidden_field_tag :assetable_type, @assignment.class, :class => 'assetable_type'
        = hidden_field_tag :assetable_id, @assignment.id, :class => 'assetable_id'
        = f.submit _('Update'), :id => 'submit_assignment', :class => 'button primary'
        = link_to _('Cancel'), lecture_assignment_path(@lecture, @assignment), :class => 'pull right'

  = render('sidebar')

app/views/coursewareable/assignments/new.html.haml
= title _('Create a new assignment')
= head_embed javascript_include_tag('edit_assignment')
= head_embed javascript_include_tag('editor')
= head_embed stylesheet_link_tag('editor')
= breadcrumbs(render('editor_breadcrumbs'))

#assignment
  .eight.columns

    = form_for(@assignment, :url => lecture_assignments_path) do |f|
      %p
        = f.label :title, _('Title')
        = f.text_field :title, :required => true

      %p
        = f.label :content, _('Content')
        = f.text_area :content, :class => 'wysiwyg-full', :required => true

      %p
        = check_box_tag :has_quiz, nil, nil, :class => 'left marginless-top expands', 'data-expand-target' => '.quiz-builder', 'data-look-allover' => 'true', 'data-toggle-class' => 'expanded'
        = label_tag :has_quiz, _('Add a quiz to this assignment')

      .hide.quiz-builder{'data-quiz' => :auto, 'data-from-store' => :false}
        = f.hidden_field :quiz, :class => 'quiz-store'
        = render(:partial => 'quiz_builder_template')

      %p
        = hidden_field_tag :assetable_type, @assignment.class, :class => 'assetable_type'
        = hidden_field_tag :assetable_id, @assignment.id, :class => 'assetable_id'
        = f.submit _('Create'), :id => 'submit_assignment', :class => 'button primary'
        = link_to _('Cancel'), lecture_path(@lecture), :class => 'pull right'

  = render('editor_sidebar')

app/views/coursewareable/assignments/show.html.haml
= title _(@assignment.title)
= breadcrumbs(render('breadcrumbs'))

#assignment
  .eight.columns.formatted

    = auto_oembed(@assignment.content).html_safe

    - if can?(:manage, @assignment) and !@assignment.quiz.blank?
      %h5
        = _('Quiz preview')

      %div.quiz-viewer
        - @assignment.quiz.each do |question|
          = render(:partial => "quiz_#{question['type']}", :locals => {:question => question})

  = render(:partial => 'sidebar')