config/routes.rb
load Rails.root.join('lib', 'subdomains.rb')

Coursewareable::Engine.routes.draw do
  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  post 'signup' => 'users#create', :as => 'signup_post'
  post 'login' => 'sessions#create', :as => 'login_post'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :passwords, :only => [
    :new, :create, :update, :edit
  ]
  resources :users, :only => [:new, :create, :update] do
    get :activate, :on => :member
    collection do
      get :me
      get :my_account
      get :invite
      post :send_invitation
      get :notifications
      put :notifications, :to => :update_notifications
      get :request_deletion
      post :request_deletion
    end
  end

  constraints(Subdomains::Allowed) do
    get 'start' => 'classrooms#new', :as => 'start_classroom'
    post 'start' => 'classrooms#create', :as => 'start_classroom_post'

    resource(:home, :path => '/', :only => [:index] ) do
      get :dashboard
      post :feedback
      post :survey
    end
  end

  constraints(Subdomains::Forbidden) do
    resource(:classroom, :path => '/', :only => [:edit, :update] ) do
      collection do
        get :dashboard, :path => '/'
        post :announce
        get :staff
        get :stats
        resources(:memberships, :only => [:index, :create, :destroy])
        resources(:collaborations, :only => [:index, :create, :destroy])
        resource(:syllabus, :only => [:show, :edit, :update, :create])
        resources(:images, :only => [:index, :create, :destroy])
        resources(:uploads, :only => [:index, :create, :destroy])
        resources(:files, :only => [:index, :destroy])
        resources(:lectures, :except => [:index]) do
          resources(:assignments, :except => [:index]) do
            resources(:grades, :only => [
              :index, :new, :create, :destroy, :edit, :update])
            resources(:responses, :only => [:new, :create, :destroy, :show])
          end
        end
      end
    end
  end

  # Route to homepage by default
  root :to => 'homes#index'
end

Courseware::Application.routes.draw do
  # Route overwrites come below:

  # Mount the Coursewareable Engine
  mount Coursewareable::Engine => '/'
end

app/controllers/coursewareable/application_controller.rb
# The [Coursewareable] namespace
module Coursewareable
  # Courseware application controller
  class ApplicationController < ::ApplicationController
    # Ask users to authenticate
    before_filter :require_login

    # Handle errors
    rescue_from CanCan::AccessDenied, :with => :unauthorized
    rescue_from ActiveRecord::RecordNotFound, :with => :not_found

    private

    # Sorcery method overwritten to customize error message
    def not_authenticated
      args = {:subdomain => request.subdomain} unless request.subdomain.blank?
      redirect_to(login_url(args), :alert => _('Please authenticate first.'))
    end

    # Unauthorized error handler
    def unauthorized
      args = {:subdomain => request.subdomain} unless request.subdomain.blank?
      redirect_to(
        login_url(args), :alert => _('Access to this page is restricted.') )
    end

    # Not found handler
    def not_found
      redirect_to('/404')
    end

    # Redirect if authenticated
    def redirect_if_loggedin
      if logged_in?
        redirect_to(root_path, :alert => _('You logged in once already.'))
      end
    end
  end
end

app/controllers/coursewareable/assignments_controller.rb
module Coursewareable
  # Assignments controller
  class AssignmentsController < ApplicationController

    # Abilities checking for our nested resource
    load_and_authorize_resource :class => Coursewareable::Assignment
    skip_authorize_resource :only => [:create, :new]

    before_filter :load_classroom_lecture

    # Handles creation screen
    def new
      @assignment = @lecture.assignments.build
      @assignment.classroom = @classroom
      @assignment.user = current_user

      authorize!(:create, @assignment)
    end

    # Handles creation
    def create
      @assignment = @lecture.assignments.build(
        params[:assignment].except(:has_quiz))

      @assignment.classroom = @classroom
      @assignment.user = current_user

      authorize!(:create, @assignment)

      unless params[:has_quiz]
        @assignment.quiz = nil
      end

      if @assignment.save
        flash[:success] = _('Assignment was created.')
        redirect_to lecture_assignment_url(
          @lecture, @assignment, :subdomain => @classroom.slug)
      else
        flash[:alert] = _('There was an error, please try again.')
        render :new
      end
    end

    # Handles assignment screen
    def show
      @assignment = @lecture.assignments.find(params[:id])
    end

    # Handles editing screen
    def edit
      @assignment = @lecture.assignments.find(params[:id])
    end

    # Handles update
    def update
      @assignment = @lecture.assignments.find(params[:id])
      @assignment.update_attributes(params[:assignment])

      unless params[:has_quiz]
        @assignment.quiz = nil
      end

      if @assignment.save
        flash[:success] = _('Assignment was updated.')
        redirect_to lecture_assignment_url(
          @lecture, @assignment, :subdomain => @classroom.slug)
      else
        flash[:alert] = _('There was an error, please try again.')
        render :edit
      end

    end

    # Handles removal
    def destroy
      assignment = @lecture.assignments.find(params[:id])

      if assignment.destroy
        flash[:success] = _('Assignment removed.')
      end

      redirect_to lecture_path(@lecture)
    end

    protected

    # Loads current classroom and lecture
    def load_classroom_lecture
      @classroom = Coursewareable::Classroom.find_by_slug!(request.subdomain)
      @lecture = @classroom.lectures.find_by_slug(params[:lecture_id])
    end
  end
end

app/controllers/coursewareable/classrooms_controller.rb
module Coursewareable
  # Classroom controller
  class ClassroomsController < ApplicationController
    # Abilities checking
    load_and_authorize_resource :class => Coursewareable::Classroom
    skip_authorize_resource

    before_filter :load_classroom, :except => [:new, :create]
    before_filter :change_header_image, :only => [:update]

    # Classroom dashboard
    # Mapped to [Classroom] subdomain
    def dashboard
      authorize!(:dashboard, @classroom)
      timeline = @classroom.all_activities
      @timeline = Kaminari.paginate_array(timeline).page(params[:page])
      render(:partial => 'shared/timeline') if request.xhr?
    end

    # Classroom creation page
    def new
      @new_classroom = current_user.created_classrooms.build
      authorize!(:create, @new_classroom)
    end

    # Customization page
    def edit
      authorize!(:update, @classroom)
    end

    # Handles submitted changes
    def update
      authorize!(:update, @classroom)

      # Remove any built temporary image
      @classroom.images.reload

      attrs = params[:classroom].except(:color_scheme, :header_image, :color)
      @classroom.update_attributes(attrs)

      redirect_to dashboard_classroom_url(:subdomain => @classroom.reload.slug)
    end

    # Handles classroom creation
    def create
      classroom = current_user.created_classrooms.build(params[:classroom])
      authorize!(:create, classroom)

      if classroom.save
        redirect_to(root_url(:subdomain => classroom.slug))
      else
        flash[:alert] =
          _('Try another classroom title or fill in all the fields.')
        redirect_to(start_classroom_path)
      end
    end

    # Handles announcement creation
    def announce
      authorize!(:contribute, @classroom)

      activity_key = 'announcement.create'
      announcement = current_user.activities_as_owner.create(
        :key => activity_key, :recipient => @classroom, :parameters => {
          :content => Sanitize.clean(params[:announcement]),
          :user_name => current_user.name
        })
      ::AnnouncementMailer.delay.new_announcement_email(announcement)
      flash[:success] = _('Announcement was posted')
      redirect_to(dashboard_classroom_path)
    end

    # Handles staff page
    def staff
      authorize!(:dashboard, @classroom)
    end

    # Handles time-series stats page
    def stats
      authorize!(:dashboard, @classroom)

      respond_to do |format|
        format.html
        format.json {
          render :json => @classroom.all_activities.select([:created_at, :key])
        }
      end
    end

    protected

    # Loads current classroom
    def load_classroom
      @classroom = Coursewareable::Classroom.find_by_slug!(request.subdomain)
    end

    # Handle uploaded header image
    def change_header_image
      authorize!(:update, @classroom)

      himg = @classroom.images.build
      himg.attachment = params[:classroom][:header_image]
      himg.description = _('New header image')
      himg.assetable = @classroom
      himg.user = current_user
      return unless himg.valid?

      ok_size = Courseware.config.header_image_size
      # Wrap this in a rescue block to avoid all kind of weird exceptions
      begin
        size = Paperclip::Geometry.from_file(params[:classroom][:header_image])
      rescue
        return
      end

      return if size.width < ok_size[:width] or size.height != ok_size[:height]

      if can?(:create, himg) and himg.save
        @classroom.update_attribute(:header_image, himg.id)
      end
    end

  end
end

app/controllers/coursewareable/collaborations_controller.rb
module Coursewareable
  # Handles Classroom collaborations
  class CollaborationsController < ApplicationController
    # Abilities checking
    load_and_authorize_resource :class => Coursewareable::Collaboration
    skip_authorize_resource

    before_filter :load_classroom

    # Handles index listing screen
    def index
      authorize!(:update, @classroom)
    end

    # Handles creation
    def create
      authorize!(:update, @classroom)
      collaboration = @classroom.collaborations.build

      collab = Coursewareable::User.where(:email => params[:email]).first
      if collab.nil?
        invitation = current_user.sent_invitations.create(
          :email => params[:email], :classroom => @classroom,
          :role => Coursewareable::Collaboration.name)
        ::CollaborationMailer.delay.new_invitation_email(invitation)
        flash[:success] = _('An invitation was sent to %s.') % params[:email]
        redirect_to(collaborations_path) and return
      end

      collaboration.user = collab
      if can?(:create, collaboration) and collaboration.save
        flash[:success] = _('%s was added to collaborators') % collab.name
        ::CollaborationMailer.delay.new_collaboration_email(collaboration)
      end

      redirect_to(collaborations_path)
    end

    # Removes a collaborator
    def destroy
      collaboration = @classroom.collaborations.find(params[:id])
      authorize!(:destroy, collaboration)

      collaboration.destroy
      redirect_to collaborations_path
    end

    protected

    # Loads current classroom
    def load_classroom
      @classroom = Coursewareable::Classroom.find_by_slug!(request.subdomain)
    end
  end
end

app/controllers/coursewareable/files_controller.rb
module Coursewareable
  # Generic uploads handler
  class FilesController < ApplicationController

    # Abilities checking for our nested resource
    load_and_authorize_resource :class => Coursewareable::Asset
    skip_authorize_resource

    before_filter :load_classroom

    # All files listing page
    def index
      authorize!(:dashboard, @classroom)

      if can?(:contribute, @classroom)
        assets = @classroom.assets.reverse
      else
        assets = @classroom.assets.where(:user_id => current_user.id).reverse
      end

      @assets = Kaminari.paginate_array(assets).page(params[:page])
      render(:partial => 'listing') if request.xhr?
    end

    # Handles deletion of a file
    def destroy
      file = @classroom.assets.find(params[:id])
      authorize!(:destroy, file)

      if file and file.destroy
        flash.now[:success] = _('File was deleted')
        flash.keep
      end

      redirect_to files_path
    end

    protected

    # Loads current classroom
    def load_classroom
      @classroom = Coursewareable::Classroom.find_by_slug!(request.subdomain)
    end
  end
end

app/controllers/coursewareable/sessions_controller.rb
module Coursewareable
  # Courseware Sessions Controller
  class SessionsController < ApplicationController

    # Do not check for abilities
    skip_load_and_authorize_resource
    # Do not ask authentication
    skip_before_filter :require_login, :except => [:destroy]
    # Redirect if logged in
    before_filter :redirect_if_loggedin, :except => [:destroy]

    # New session screen handler
    def new
    end

    # New session handler
    def create
      user = login(params[:email], params[:password], params[:remember_me])
      subdomain = request.subdomain unless request.subdomain.blank? || false
      if user
        flash[:notice] = _('Welcome back %{name}!' % {:name => user.name})
        redirect_back_or_to(root_url(:subdomain => subdomain))
      else
        flash.now.alert = _('Email or password was invalid.')
        render :new
      end
    end

    # Destroys session, aka logout
    def destroy
      logout
      subdomain = request.subdomain unless request.subdomain.blank? || false
      redirect_to root_url(:subdomain => subdomain), :notice => _('Logged out!')
    end
  end
end

app/helpers/coursewareable/application_helper.rb
module Coursewareable
  # Courseware helpers
  module ApplicationHelper
    # Helper to set page title
    #
    # @param [String] page_title
    def title(page_title)
      content_for(:title, page_title) if page_title
    end

    # Helper to set embeds in HEAD
    #
    # @param [String] content
    def head_embed(content)
      content_for(:head_embed, content) if content
    end

    # Helper to set breadcrumbs content
    #
    # @param [String] content
    def breadcrumbs(content)
      content_for(:breadcrumbs, content) if content
    end

    # Helper to render the classroom header image
    # Defaults to a randomly provided image
    #
    # @return [String], generated style tag with CSS
    def header_image
      return if @classroom.nil? or @classroom.new_record?

      image = @classroom.images.find_by_id(@classroom.header_image)
      return if image.nil?

      @header_image = image.attachment.url
      render('shared/header_image')
    end

    # Generates a random header image from available list
    # Uses last classroom digit from it's ID
    #
    # @return [String], generated style tag with CSS
    def default_header_image
      return if @classroom.nil? or @classroom.new_record?

      image_id = @classroom.id % 10

      # Since we have only 1..7 available headers, lets map what doesn't fit
      image_id = 7 if image_id == 0 or image_id > 7
      @header_image = path_to_image("headers/#{image_id}.jpg")
      render('shared/header_image')
    end

    # Turns all http(s) URLs into HTML content if URL is an oembed link
    #
    # @param [String] text, the text to be checked for URLs
    # @return [String], the updated `text` with oembed content
    def auto_oembed(text)
      return ''.html_safe if text.blank?

      content = {}
      urls = URI.extract(text, %w(http https))

      return text.html_safe unless urls.count > 0

      urls.each do |url|
        html = fetch_and_render_oembed(url)
        content[url] = html unless html.blank?
      end

      content.each_pair do |key, value|
        text.sub!(key, value)
      end

      return text.html_safe
    end

    private

    # Tries to fetch `url` content from oembed providers
    # On success renders a partial from `shared/auto_oembed` based on
    # provider response type.
    #
    # @param [String] url, the URL to be checked
    # @return [String], the rendered partial content
    def fetch_and_render_oembed(url)
      begin
        response = OEmbed::Providers.get(url.to_str)
      rescue
        response = nil
      end

      render(
        :partial => "auto_oembed/#{response.type}",
        :locals => {:oembed => response}
      ) unless response.nil?
    end

  end
end

app/helpers/coursewareable/lectures_helper.rb
module Coursewareable
  # Courseware lectures controller helpers
  module LecturesHelper
    # Outputs a hierarchical structure of lectures based on its parent/children
    def list_lecture_options(lectures, selected=nil, listed_ids=[], indent='')
      return if lectures.nil?

      output = ''
      lectures.each do |lecture|
        unless listed_ids.include?(lecture.id)
          listed_ids.push(lecture.id)
          output += render(:partial => 'lecture_options', :locals => {
            :lecture => lecture, :listed_ids => listed_ids, :indent => indent,
            :selected => selected})
        end
      end
      return output.html_safe
    end
  end
end

app/helpers/coursewareable/syllabuses_helper.rb
module Coursewareable
  # Courseware syllabuses controller helpers
  module SyllabusesHelper
    # Outputs a hierarchical structure of lectures based on its parent/children
    def list_lectures_tree(lectures, listed_ids = [])
      output = ''
      lectures.each do |lecture|
        unless listed_ids.include?(lecture.id)
          listed_ids.push(lecture.id)
          output += render(:partial => 'lectures_listing', :locals => {
            :lecture => lecture, :listed_ids => listed_ids})
        end
      end
      return output.html_safe
    end
  end
end

app/views/coursewareable/grades/_breadcrumbs.html.haml
.twelve.columns
  %ul.breadcrumbs
    %li
      = link_to(_('Syllabus'), syllabus_path)
    %li
      = link_to(@lecture.title, lecture_path(@lecture))
    %li
      = link_to(@assignment.title, lecture_assignment_path(@lecture, @assignment))
    - if @grade.nil?
      %li.current
        %span
          = _('Gradebook')
    - else
      %li
        %span
          = link_to(_('Gradebook'), lecture_assignment_grades_path(@lecture, @assignment))
      %li.current
        %span
          - if @grade.new_record?
            = _('You are adding a new grade')
          - else
            = _('%s grade') % @grade.receiver.name

app/views/coursewareable/grades/_sidebar.html.haml
.four.columns
  .row.sidebar
    %h5
      = _('Assignment grades')
    %hr

    - if !@grade.nil? and !@grade.new_record?
      %p.smaller
        = _('This grade was added by %s on %s') % [@grade.user.name, @grade.updated_at.to_s(:pretty)]
      %hr

    %ul.itemized
      %li
        %strong
          = link_to(_('Add a new grade'), new_lecture_assignment_grade_path(@lecture, @assignment), :id => 'new_grade')
      - if !@assignment.grades.limit(5).empty? and @grades.nil?
        - @assignment.grades.limit(5).each do |grade|
          %li
            = link_to(_('%s grade') % grade.receiver.name, lecture_assignment_grade_path(@lecture, @assignment, grade))
      - if !@assignment.grades.offset(5).empty? and @grades.nil?
        %li
          = link_to(_('Including %d more...') % @assignment.grades.offset(5).count, lecture_assignment_grades_path(@lecture, @assignment))
      - if !@grades.nil?
        %li
          = link_to(_('Grades assignment'), lecture_assignment_path(@lecture, @assignment))
        %li
          = link_to(_('Grades lecture'), lecture_path(@lecture))

app/views/coursewareable/grades/edit.html.haml
= title _('Update %s\'s grade') % @grade.receiver.name
= breadcrumbs(render('breadcrumbs'))

#grade
  .eight.columns

    %h4
      %span.avatar
        = gravatar_image_tag(@grade.receiver.email, :alt => @grade.receiver.name, :gravatar => { :size => 25 })
      = _('%s grade') % @grade.receiver.name
    %hr

    = form_for(@grade, :url => lecture_assignment_grade_path) do |f|
      .row
        .four.columns
          = f.label :form, _('Format'), :class => 'left four inline'
          = f.select :form, @forms, {:selected => @grade.form}, {:required => true, :class => 'eight inline'}

        .three.columns.align-right
          = f.label :mark, _('Grade'), :class => 'left six inline'
          = f.text_field :mark, {:required => true, :class => 'five right inline'}
        .five.columns.align-right

      %p
        = f.label :comment, _('If you have feedback to add, fill in below')
        = f.text_area :comment, :rows => 4

      %p
        = f.submit _('Save'), :id => 'update_grade', :class => 'button primary'
        = link_to _('Cancel'), lecture_assignment_grades_path, :class => 'pull right'

  = render(:partial => 'sidebar')

app/views/coursewareable/grades/index.html.haml
= title _('Assignment grades')
= breadcrumbs(render('breadcrumbs'))

#grade
  .eight.columns

    - grades_title = pluralize(@grades.count, _('grade'), _('grades'))
    %h4
      = _('%s for this assignment') % grades_title
    %hr

    - if @grades.empty?
      %p
        != _('Sorry there are no grades so far. %s?') % link_to(_('Want to add one'), new_lecture_assignment_grade_path(@lecture, @assignment))

    - else
      %table.twelve
        %thead
          %tr
            %th
              = _('Name')
            %th
              = _('Grade')
            %th
              = _('Response')
            %th
              = _('Assignment')
        %tbody
          - @grades.each do |grade|
            %tr{:id => "grade-#{grade.id}"}
              %td.avatar
                = gravatar_image_tag(grade.receiver.email, :alt => grade.receiver.name, :gravatar => { :size => 20 })
                = grade.receiver.name
              %td
                = grade.mark.to_s + (grade.form == 'percent' ? '%' : '')
                = link_to('', edit_lecture_assignment_grade_path(@lecture, @assignment, grade), :class => 'right icon-edit', :id => "update_grade-#{grade.id}", :title => 'Update this grade')
              %td
                -#TODO: improve the response-vs-grade linkage workflow
                -# - if grade.response.nil?
                = _('No response linked.')
                -# - else
                -#   = link_to((_('%s') % grade.response.id), lecture_assignment_response_path(@lecture, @assignment, grade.response))
              %td
                = link_to(truncate(@assignment.title, :length => 30), lecture_assignment_path(@lecture, @assignment))

  = render(:partial => 'sidebar')

app/views/coursewareable/grades/new.html.haml
= title _('Add a new grade')
= breadcrumbs(render('breadcrumbs'))

#grade
  .eight.columns

    %h4
      = _('Add a new grade')
    %hr

    = form_for(@grade, :url => lecture_assignment_grades_path) do |f|
      .row
        .four.columns
          = f.label :form, _('Format'), :class => 'left four inline'
          = f.select :form, @forms, {:selected => @grade.form}, {:required => true, :class => 'eight inline'}

        .three.columns.align-right
          = f.label :mark, _('Grade'), :class => 'left six inline'
          = f.text_field :mark, {:required => true, :class => 'five right inline'}

        .five.columns.align-right
          = f.label :receiver_id, _('User'), :class => 'left three inline'
          = f.select :receiver_id, @members, {}, {:required => true, :class => 'eight right inline'}

      %p
        = f.label :comment, _('If you have feedback to add, fill in below')
        = f.text_area :comment, :rows => 4

      %p
        = f.submit _('Add'), :id => 'submit_grade', :class => 'button primary'
        = link_to _('Cancel'), lecture_assignment_grades_path, :class => 'pull right'

  = render(:partial => 'sidebar')