config/routes.rb
load Rails.root.join('lib', 'subdomains.rb')

Coursewareable::Engine.routes.draw do
  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  post 'signup' => 'users#create', :as => 'signup_post'
  post 'login' => 'sessions#create', :as => 'login_post'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :passwords, :only => [
    :new, :create, :update, :edit
  ]
  resources :users, :only => [:new, :create, :update] do
    get :activate, :on => :member
    collection do
      get :me
      get :my_account
      get :invite
      post :send_invitation
      get :notifications
      put :notifications, :to => :update_notifications
      get :request_deletion
      post :request_deletion
    end
  end

  constraints(Subdomains::Allowed) do
    get 'start' => 'classrooms#new', :as => 'start_classroom'
    post 'start' => 'classrooms#create', :as => 'start_classroom_post'

    resource(:home, :path => '/', :only => [:index] ) do
      get :dashboard
      post :feedback
      post :survey
    end
  end

  constraints(Subdomains::Forbidden) do
    resource(:classroom, :path => '/', :only => [:edit, :update] ) do
      collection do
        get :dashboard, :path => '/'
        post :announce
        get :staff
        get :stats
        resources(:memberships, :only => [:index, :create, :destroy])
        resources(:collaborations, :only => [:index, :create, :destroy])
        resource(:syllabus, :only => [:show, :edit, :update, :create])
        resources(:images, :only => [:index, :create, :destroy])
        resources(:uploads, :only => [:index, :create, :destroy])
        resources(:files, :only => [:index, :destroy])
        resources(:lectures, :except => [:index]) do
          resources(:assignments, :except => [:index]) do
            resources(:grades, :only => [
              :index, :new, :create, :destroy, :edit, :update])
            resources(:responses, :only => [:new, :create, :destroy, :show])
          end
        end
      end
    end
  end

  # Route to homepage by default
  root :to => 'homes#index'
end

Courseware::Application.routes.draw do
  # Route overwrites come below:

  # Mount the Coursewareable Engine
  mount Coursewareable::Engine => '/'
end

app/views/shared/_alerts.html.haml
%div#notifications.row
  %div.six.columns.end.centered
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        %div.align-center{ :class => "alert-box #{name}" }
          = msg
          %a.close.icon-remove{ :href => '#' }

app/views/shared/_classroom_customization_tabs.html.haml
%dl.tabs
  %dd{:class => current_page?(edit_classroom_path) ? 'active' : nil}
    = link_to(_('Customize classroom'), edit_classroom_path)
  %dd{:class => current_page?(memberships_path) ? 'active' : nil}
    = link_to(_('Manage users'), memberships_path)
  %dd{:class => current_page?(collaborations_path) ? 'active' : nil}
    = link_to(_('Manage collaborators'), collaborations_path)

app/views/shared/_classroom_menu.html.haml
- if can?(:contribute, @classroom)
  - files_count = @classroom.assets.count
- else
  - files_count = @classroom.assets.where(:user_id => current_user.id).count

.row
  .twelve.columns
    %ul
      %li{:class => (current_page?(dashboard_classroom_path) ? 'current' : '')}
        = link_to(_('Timeline'), dashboard_classroom_path)
      %li{:class => (request.fullpath.match(/syllabus|lecture/) ? 'current' : '')}
        = link_to(_('Syllabus'), syllabus_path)

      - if files_count > 0
        %li{:class => (current_page?(files_path) ? 'current' : '')}
          = link_to(_('%d Files') % files_count, files_path)

      %li{:class => (current_page?(staff_classroom_path) ? 'current' : '')}
        = link_to(_('Staff'), staff_classroom_path)

      %li{:class => (current_page?(stats_classroom_path) ? 'current' : '')}
        = link_to(_('Stats'), stats_classroom_path)

app/views/shared/_feedback.html.haml
.feedback
  #feedbackModal.reveal-modal.medium.hide
    %a{:class => 'close-reveal-modal'}
      &#215;

    %h4
      = _('Hey %s,') % current_user.name
    %p
      = _('please tell us what would make Courseware better!')

    = form_tag survey_home_url(:subdomain => false), :id => 'survey' do
      .row
        .six.columns
          .row
            = radio_button_tag(:category, :force_majeure, nil, :class => 'left inline')
            = label_tag(:category_force_majeure, _('Errors or unexpected behavior'), :class => 'smaller left inline marginless-bottom')
          .row
            = radio_button_tag(:category, :ui_ux, true, :class => 'left inline')
            = label_tag(:category_ui_ux, _('Interface and design'), :class => 'smaller left inline marginless-bottom')
        .six.columns
          .row
            = radio_button_tag(:category, :features, nil, :class => 'left inline')
            = label_tag(:category_features, _('Suggestions and features'), :class => 'smaller left inline marginless-bottom')
          .row
            = radio_button_tag(:category, :other, nil, :class => 'left inline')
            = label_tag(:category_other, _('Other issues'), :class => 'smaller left inline marginless-bottom')

      = hidden_field_tag(:current_path, request.url)
      = text_area_tag(:message, nil, :required => true, :placeholder => _('Hey guys, check this out...'))

      = submit_tag(_('Send this'), :class => 'button small primary', :id => 'submit_survey')

app/views/shared/_footer.html.haml
%footer{:role => :contentinfo}
  %div.row
    .six.columns
      %p
    .six.columns.align-right
      %p
        != _('With %s from Transylvania') % '<span class="icon-heart heart"></span>'

app/views/shared/_header_image.html.haml
:css
  #heading .custom {
    background: url("#{@header_image}") top center no-repeat !important;
  }

app/views/shared/_sidebar_lectures_listing.html.haml
- max_child_count = 3
%ul.itemized
  - if can?(:contribute, classroom)
    %li
      %strong
        = link_to(_('Add a new lecture'), new_lecture_path)
  - lectures.each do |lecture|
    - unless lecture.parent_lecture
      %li
        - unless lecture.child_lectures.empty?
          = link_to('', '#', :class => 'icon-plus right expands', 'data-expand-target' => '.child-lectures-listing', 'data-toggle-class' => 'icon-minus')

        = link_to(lecture.title, lecture_path(lecture))
        - unless lecture.child_lectures.empty?
          .child-lectures-listing.hide
            %ul
              - child_lectures = lecture.child_lectures.limit(max_child_count)
              - child_lectures.each do |child_lecture|
                %li
                  = link_to(child_lecture.title, lecture_path(child_lecture))

                - if child_lectures.last.eql?(child_lecture)
                  - remaining = lecture.child_lectures.offset(max_child_count).count
                  - if remaining > 0
                    %p.marginless-bottom.smaller
                      - lec_title = pluralize(remaining, _('more lecture'), _('more lectures'))
                      != _('Including %s.') % link_to(lec_title, '#lectures-tree')

app/views/shared/_timeline.html.haml
- last_timestamp = nil

- @timeline.each do |event|
  - @icon_name = ''
  - activity_content = render_activity(event, :current_user => current_user)
  - if last_timestamp != event.created_at.to_date
    - last_timestamp = event.created_at.to_date
    .row
      .twelve.columns
        %h5
          - if last_timestamp.today?
            = _('Today')
          - elsif last_timestamp == Date.yesterday
            = _('Yesterday')
          - else
            = event.created_at.to_s(:pretty_date)
        %hr

  .row
    .two.columns.timestamp.smaller.align-left
      = event.created_at.to_s(:pretty_time)

    .one.columns.align-right.backgroundify
      %span{:class => @icon_name}

    .nine.columns.end.activity
      = activity_content
      %hr

= paginate(@timeline, {:run_as_xhr => true, :next_title => _('More') })

app/views/shared/_topbar.html.haml
- if logged_in?
  = render('shared/feedback')

.row
  .six.columns
    %a{:href => root_url(:subdomain => false)}
      = image_tag('courseware.png', :alt => 'The Courseware Project')
  .three.offset-by-three.columns.align-right
    - if logged_in?
      .feedback
        = link_to(_('Send feedback'), '#', 'data-reveal-id' => 'feedbackModal', :class => 'modal-trigger button simple tiny')

      .small.button.dropdown.naked
        %a{:href => '#'}
          .avatar
            = gravatar_image_tag(current_user.email, :alt => current_user.name, :gravatar => {:size => 32})
        %span
        %ul
          - if logged_in?
            %li
              = link_to _('Dashboard'), dashboard_home_url(:subdomain => false)
            %li
              = link_to _('Profile'), me_users_url(:subdomain => false)
            %li
              = link_to _('Account'), my_account_users_url(:subdomain => false)
            %li
              = link_to _('Delete account'), request_deletion_users_url(:subdomain => false)
            %li
              = link_to _('Invite a friend'), invite_users_url(:subdomain => false)
            %li
              = link_to _('Logout'), logout_path