config/routes.rb
load Rails.root.join('lib', 'subdomains.rb')

Coursewareable::Engine.routes.draw do
  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  post 'signup' => 'users#create', :as => 'signup_post'
  post 'login' => 'sessions#create', :as => 'login_post'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :passwords, :only => [
    :new, :create, :update, :edit
  ]
  resources :users, :only => [:new, :create, :update] do
    get :activate, :on => :member
    collection do
      get :me
      get :my_account
      get :invite
      post :send_invitation
      get :notifications
      put :notifications, :to => :update_notifications
      get :request_deletion
      post :request_deletion
    end
  end

  constraints(Subdomains::Allowed) do
    get 'start' => 'classrooms#new', :as => 'start_classroom'
    post 'start' => 'classrooms#create', :as => 'start_classroom_post'

    resource(:home, :path => '/', :only => [:index] ) do
      get :dashboard
      post :feedback
      post :survey
    end
  end

  constraints(Subdomains::Forbidden) do
    resource(:classroom, :path => '/', :only => [:edit, :update] ) do
      collection do
        get :dashboard, :path => '/'
        post :announce
        get :staff
        get :stats
        resources(:memberships, :only => [:index, :create, :destroy])
        resources(:collaborations, :only => [:index, :create, :destroy])
        resource(:syllabus, :only => [:show, :edit, :update, :create])
        resources(:images, :only => [:index, :create, :destroy])
        resources(:uploads, :only => [:index, :create, :destroy])
        resources(:files, :only => [:index, :destroy])
        resources(:lectures, :except => [:index]) do
          resources(:assignments, :except => [:index]) do
            resources(:grades, :only => [
              :index, :new, :create, :destroy, :edit, :update])
            resources(:responses, :only => [:new, :create, :destroy, :show])
          end
        end
      end
    end
  end

  # Route to homepage by default
  root :to => 'homes#index'
end

Courseware::Application.routes.draw do
  # Route overwrites come below:

  # Mount the Coursewareable Engine
  mount Coursewareable::Engine => '/'
end

app/controllers/coursewareable/application_controller.rb
# The [Coursewareable] namespace
module Coursewareable
  # Courseware application controller
  class ApplicationController < ::ApplicationController
    # Ask users to authenticate
    before_filter :require_login

    # Handle errors
    rescue_from CanCan::AccessDenied, :with => :unauthorized
    rescue_from ActiveRecord::RecordNotFound, :with => :not_found

    private

    # Sorcery method overwritten to customize error message
    def not_authenticated
      args = {:subdomain => request.subdomain} unless request.subdomain.blank?
      redirect_to(login_url(args), :alert => _('Please authenticate first.'))
    end

    # Unauthorized error handler
    def unauthorized
      args = {:subdomain => request.subdomain} unless request.subdomain.blank?
      redirect_to(
        login_url(args), :alert => _('Access to this page is restricted.') )
    end

    # Not found handler
    def not_found
      redirect_to('/404')
    end

    # Redirect if authenticated
    def redirect_if_loggedin
      if logged_in?
        redirect_to(root_path, :alert => _('You logged in once already.'))
      end
    end
  end
end

app/controllers/coursewareable/assignments_controller.rb
module Coursewareable
  # Assignments controller
  class AssignmentsController < ApplicationController

    # Abilities checking for our nested resource
    load_and_authorize_resource :class => Coursewareable::Assignment
    skip_authorize_resource :only => [:create, :new]

    before_filter :load_classroom_lecture

    # Handles creation screen
    def new
      @assignment = @lecture.assignments.build
      @assignment.classroom = @classroom
      @assignment.user = current_user

      authorize!(:create, @assignment)
    end

    # Handles creation
    def create
      @assignment = @lecture.assignments.build(
        params[:assignment].except(:has_quiz))

      @assignment.classroom = @classroom
      @assignment.user = current_user

      authorize!(:create, @assignment)

      unless params[:has_quiz]
        @assignment.quiz = nil
      end

      if @assignment.save
        flash[:success] = _('Assignment was created.')
        redirect_to lecture_assignment_url(
          @lecture, @assignment, :subdomain => @classroom.slug)
      else
        flash[:alert] = _('There was an error, please try again.')
        render :new
      end
    end

    # Handles assignment screen
    def show
      @assignment = @lecture.assignments.find(params[:id])
    end

    # Handles editing screen
    def edit
      @assignment = @lecture.assignments.find(params[:id])
    end

    # Handles update
    def update
      @assignment = @lecture.assignments.find(params[:id])
      @assignment.update_attributes(params[:assignment])

      unless params[:has_quiz]
        @assignment.quiz = nil
      end

      if @assignment.save
        flash[:success] = _('Assignment was updated.')
        redirect_to lecture_assignment_url(
          @lecture, @assignment, :subdomain => @classroom.slug)
      else
        flash[:alert] = _('There was an error, please try again.')
        render :edit
      end

    end

    # Handles removal
    def destroy
      assignment = @lecture.assignments.find(params[:id])

      if assignment.destroy
        flash[:success] = _('Assignment removed.')
      end

      redirect_to lecture_path(@lecture)
    end

    protected

    # Loads current classroom and lecture
    def load_classroom_lecture
      @classroom = Coursewareable::Classroom.find_by_slug!(request.subdomain)
      @lecture = @classroom.lectures.find_by_slug(params[:lecture_id])
    end
  end
end

app/controllers/coursewareable/classrooms_controller.rb
module Coursewareable
  # Classroom controller
  class ClassroomsController < ApplicationController
    # Abilities checking
    load_and_authorize_resource :class => Coursewareable::Classroom
    skip_authorize_resource

    before_filter :load_classroom, :except => [:new, :create]
    before_filter :change_header_image, :only => [:update]

    # Classroom dashboard
    # Mapped to [Classroom] subdomain
    def dashboard
      authorize!(:dashboard, @classroom)
      timeline = @classroom.all_activities
      @timeline = Kaminari.paginate_array(timeline).page(params[:page])
      render(:partial => 'shared/timeline') if request.xhr?
    end

    # Classroom creation page
    def new
      @new_classroom = current_user.created_classrooms.build
      authorize!(:create, @new_classroom)
    end

    # Customization page
    def edit
      authorize!(:update, @classroom)
    end

    # Handles submitted changes
    def update
      authorize!(:update, @classroom)

      # Remove any built temporary image
      @classroom.images.reload

      attrs = params[:classroom].except(:color_scheme, :header_image, :color)
      @classroom.update_attributes(attrs)

      redirect_to dashboard_classroom_url(:subdomain => @classroom.reload.slug)
    end

    # Handles classroom creation
    def create
      classroom = current_user.created_classrooms.build(params[:classroom])
      authorize!(:create, classroom)

      if classroom.save
        redirect_to(root_url(:subdomain => classroom.slug))
      else
        flash[:alert] =
          _('Try another classroom title or fill in all the fields.')
        redirect_to(start_classroom_path)
      end
    end

    # Handles announcement creation
    def announce
      authorize!(:contribute, @classroom)

      activity_key = 'announcement.create'
      announcement = current_user.activities_as_owner.create(
        :key => activity_key, :recipient => @classroom, :parameters => {
          :content => Sanitize.clean(params[:announcement]),
          :user_name => current_user.name
        })
      ::AnnouncementMailer.delay.new_announcement_email(announcement)
      flash[:success] = _('Announcement was posted')
      redirect_to(dashboard_classroom_path)
    end

    # Handles staff page
    def staff
      authorize!(:dashboard, @classroom)
    end

    # Handles time-series stats page
    def stats
      authorize!(:dashboard, @classroom)

      respond_to do |format|
        format.html
        format.json {
          render :json => @classroom.all_activities.select([:created_at, :key])
        }
      end
    end

    protected

    # Loads current classroom
    def load_classroom
      @classroom = Coursewareable::Classroom.find_by_slug!(request.subdomain)
    end

    # Handle uploaded header image
    def change_header_image
      authorize!(:update, @classroom)

      himg = @classroom.images.build
      himg.attachment = params[:classroom][:header_image]
      himg.description = _('New header image')
      himg.assetable = @classroom
      himg.user = current_user
      return unless himg.valid?

      ok_size = Courseware.config.header_image_size
      # Wrap this in a rescue block to avoid all kind of weird exceptions
      begin
        size = Paperclip::Geometry.from_file(params[:classroom][:header_image])
      rescue
        return
      end

      return if size.width < ok_size[:width] or size.height != ok_size[:height]

      if can?(:create, himg) and himg.save
        @classroom.update_attribute(:header_image, himg.id)
      end
    end

  end
end

app/controllers/coursewareable/collaborations_controller.rb
module Coursewareable
  # Handles Classroom collaborations
  class CollaborationsController < ApplicationController
    # Abilities checking
    load_and_authorize_resource :class => Coursewareable::Collaboration
    skip_authorize_resource

    before_filter :load_classroom

    # Handles index listing screen
    def index
      authorize!(:update, @classroom)
    end

    # Handles creation
    def create
      authorize!(:update, @classroom)
      collaboration = @classroom.collaborations.build

      collab = Coursewareable::User.where(:email => params[:email]).first
      if collab.nil?
        invitation = current_user.sent_invitations.create(
          :email => params[:email], :classroom => @classroom,
          :role => Coursewareable::Collaboration.name)
        ::CollaborationMailer.delay.new_invitation_email(invitation)
        flash[:success] = _('An invitation was sent to %s.') % params[:email]
        redirect_to(collaborations_path) and return
      end

      collaboration.user = collab
      if can?(:create, collaboration) and collaboration.save
        flash[:success] = _('%s was added to collaborators') % collab.name
        ::CollaborationMailer.delay.new_collaboration_email(collaboration)
      end

      redirect_to(collaborations_path)
    end

    # Removes a collaborator
    def destroy
      collaboration = @classroom.collaborations.find(params[:id])
      authorize!(:destroy, collaboration)

      collaboration.destroy
      redirect_to collaborations_path
    end

    protected

    # Loads current classroom
    def load_classroom
      @classroom = Coursewareable::Classroom.find_by_slug!(request.subdomain)
    end
  end
end

app/controllers/coursewareable/files_controller.rb
module Coursewareable
  # Generic uploads handler
  class FilesController < ApplicationController

    # Abilities checking for our nested resource
    load_and_authorize_resource :class => Coursewareable::Asset
    skip_authorize_resource

    before_filter :load_classroom

    # All files listing page
    def index
      authorize!(:dashboard, @classroom)

      if can?(:contribute, @classroom)
        assets = @classroom.assets.reverse
      else
        assets = @classroom.assets.where(:user_id => current_user.id).reverse
      end

      @assets = Kaminari.paginate_array(assets).page(params[:page])
      render(:partial => 'listing') if request.xhr?
    end

    # Handles deletion of a file
    def destroy
      file = @classroom.assets.find(params[:id])
      authorize!(:destroy, file)

      if file and file.destroy
        flash.now[:success] = _('File was deleted')
        flash.keep
      end

      redirect_to files_path
    end

    protected

    # Loads current classroom
    def load_classroom
      @classroom = Coursewareable::Classroom.find_by_slug!(request.subdomain)
    end
  end
end

app/controllers/coursewareable/sessions_controller.rb
module Coursewareable
  # Courseware Sessions Controller
  class SessionsController < ApplicationController

    # Do not check for abilities
    skip_load_and_authorize_resource
    # Do not ask authentication
    skip_before_filter :require_login, :except => [:destroy]
    # Redirect if logged in
    before_filter :redirect_if_loggedin, :except => [:destroy]

    # New session screen handler
    def new
    end

    # New session handler
    def create
      user = login(params[:email], params[:password], params[:remember_me])
      subdomain = request.subdomain unless request.subdomain.blank? || false
      if user
        flash[:notice] = _('Welcome back %{name}!' % {:name => user.name})
        redirect_back_or_to(root_url(:subdomain => subdomain))
      else
        flash.now.alert = _('Email or password was invalid.')
        render :new
      end
    end

    # Destroys session, aka logout
    def destroy
      logout
      subdomain = request.subdomain unless request.subdomain.blank? || false
      redirect_to root_url(:subdomain => subdomain), :notice => _('Logged out!')
    end
  end
end

app/helpers/coursewareable/application_helper.rb
module Coursewareable
  # Courseware helpers
  module ApplicationHelper
    # Helper to set page title
    #
    # @param [String] page_title
    def title(page_title)
      content_for(:title, page_title) if page_title
    end

    # Helper to set embeds in HEAD
    #
    # @param [String] content
    def head_embed(content)
      content_for(:head_embed, content) if content
    end

    # Helper to set breadcrumbs content
    #
    # @param [String] content
    def breadcrumbs(content)
      content_for(:breadcrumbs, content) if content
    end

    # Helper to render the classroom header image
    # Defaults to a randomly provided image
    #
    # @return [String], generated style tag with CSS
    def header_image
      return if @classroom.nil? or @classroom.new_record?

      image = @classroom.images.find_by_id(@classroom.header_image)
      return if image.nil?

      @header_image = image.attachment.url
      render('shared/header_image')
    end

    # Generates a random header image from available list
    # Uses last classroom digit from it's ID
    #
    # @return [String], generated style tag with CSS
    def default_header_image
      return if @classroom.nil? or @classroom.new_record?

      image_id = @classroom.id % 10

      # Since we have only 1..7 available headers, lets map what doesn't fit
      image_id = 7 if image_id == 0 or image_id > 7
      @header_image = path_to_image("headers/#{image_id}.jpg")
      render('shared/header_image')
    end

    # Turns all http(s) URLs into HTML content if URL is an oembed link
    #
    # @param [String] text, the text to be checked for URLs
    # @return [String], the updated `text` with oembed content
    def auto_oembed(text)
      return ''.html_safe if text.blank?

      content = {}
      urls = URI.extract(text, %w(http https))

      return text.html_safe unless urls.count > 0

      urls.each do |url|
        html = fetch_and_render_oembed(url)
        content[url] = html unless html.blank?
      end

      content.each_pair do |key, value|
        text.sub!(key, value)
      end

      return text.html_safe
    end

    private

    # Tries to fetch `url` content from oembed providers
    # On success renders a partial from `shared/auto_oembed` based on
    # provider response type.
    #
    # @param [String] url, the URL to be checked
    # @return [String], the rendered partial content
    def fetch_and_render_oembed(url)
      begin
        response = OEmbed::Providers.get(url.to_str)
      rescue
        response = nil
      end

      render(
        :partial => "auto_oembed/#{response.type}",
        :locals => {:oembed => response}
      ) unless response.nil?
    end

  end
end

app/helpers/coursewareable/lectures_helper.rb
module Coursewareable
  # Courseware lectures controller helpers
  module LecturesHelper
    # Outputs a hierarchical structure of lectures based on its parent/children
    def list_lecture_options(lectures, selected=nil, listed_ids=[], indent='')
      return if lectures.nil?

      output = ''
      lectures.each do |lecture|
        unless listed_ids.include?(lecture.id)
          listed_ids.push(lecture.id)
          output += render(:partial => 'lecture_options', :locals => {
            :lecture => lecture, :listed_ids => listed_ids, :indent => indent,
            :selected => selected})
        end
      end
      return output.html_safe
    end
  end
end

app/helpers/coursewareable/syllabuses_helper.rb
module Coursewareable
  # Courseware syllabuses controller helpers
  module SyllabusesHelper
    # Outputs a hierarchical structure of lectures based on its parent/children
    def list_lectures_tree(lectures, listed_ids = [])
      output = ''
      lectures.each do |lecture|
        unless listed_ids.include?(lecture.id)
          listed_ids.push(lecture.id)
          output += render(:partial => 'lectures_listing', :locals => {
            :lecture => lecture, :listed_ids => listed_ids})
        end
      end
      return output.html_safe
    end
  end
end

app/views/coursewareable/classrooms/_edit_sidebar.html.haml
.four.columns
  .row.sidebar

    %h5
      = _('Classroom customization')

    %hr

    %p
      = _('Since you are the classroom owner you can customize some of the details.')

    %p
      != _('All the uploaded header images can later be found under the %s.') % link_to(_('files menu'), files_path)

app/views/coursewareable/classrooms/_sidebar.html.haml
.four.columns
  .row.sidebar
    - if can?(:contribute, @classroom)
      = render('sidebar_collaborator')
    - else

      %h5
        = _('About this classroom')
      %hr

      - if @classroom.syllabus and !@classroom.syllabus.intro.blank?
        = auto_oembed(simple_format(@classroom.syllabus.intro)).html_safe
      - else
        = auto_oembed(simple_format(@classroom.description)).html_safe

      - unless @classroom.lectures.empty?
        %h5
          = _('Lectures')
        %hr

        = render(:partial => 'shared/sidebar_lectures_listing', :locals => {:lectures => @classroom.lectures, :classroom => @classroom})

      %h5
        = _('Your progress')
      %hr

      - responses_count = current_user.responses.where(:classroom_id => @classroom.id).count
      - assignments_count = @classroom.assignments.count
      - coverage = ((responses_count * 100) / assignments_count) if assignments_count > 0

      .nice.success.progress
        %span.meter{:style => "width: #{coverage.to_i}%"}

      %p.smaller.align-center
        = _('%d responses out of %d assignments') % [responses_count, assignments_count ]

      %hr

      %ul.itemized
        %li
          %span.icon-users
            = pluralize(@classroom.memberships_count, _('member'), _('members'))
        %li
          %span.icon-book
            = link_to(pluralize(@classroom.lectures.count, _('lecture'), _('lectures')), syllabus_path)
        %li
          %span.icon-newspaper
            = pluralize(@classroom.assignments.count, _('assignment'), _('assignments'))
        %li
          %span.icon-docs
            = pluralize(@classroom.responses.count, _('response'), _('responses'))
        %li
          %span.icon-trophy
            = pluralize(@classroom.grades.count, _('grade'), _('grades'))

app/views/coursewareable/classrooms/_sidebar_collaborator.html.haml
%h5
  - if can?(:update, @classroom)
    %a.icon-settings.right{:href => edit_classroom_path, :title => _('Manage this classroom')}
  = _('About this classroom')
%hr

- if @classroom.syllabus and @classroom.syllabus.intro
  = auto_oembed(simple_format(@classroom.syllabus.intro)).html_safe
- else
  %p
    != _('Next: %s.') % link_to(_('update the syllabus'), edit_syllabus_path)

- if current_page?(dashboard_classroom_path)
  %p.icon-announce
    != _('Got something important to say, %s.') % link_to(_('write an announcement'), '#', :class => 'expands', 'data-expand-target' => '#announce', 'data-look-allover' => 'true' )

%hr

%ul.itemized
  %li
    %span.icon-users
      = link_to(pluralize(@classroom.memberships_count, _('member'), _('members')), memberships_path)
  %li
    %span.icon-book
      = link_to(pluralize(@classroom.lectures.count, _('lecture'), _('lectures')), syllabus_path)
  %li
    %span.icon-newspaper
      = pluralize(@classroom.assignments.count, _('assignment'), _('assignments'))
  %li
    %span.icon-docs
      = pluralize(@classroom.responses.count, _('response'), _('responses'))
  %li
    %span.icon-trophy
      = pluralize(@classroom.grades.count, _('grade'), _('grades'))

app/views/coursewareable/classrooms/dashboard.html.haml
= title  _('Timeline for %s') % @classroom.title

#activities
  .eight.columns

    - if can?(:contribute, @classroom)
      = form_tag(announce_classroom_path, :id => :announce, :class => 'hide') do
        = text_area_tag(:announcement, nil, :required => true, :placeholder => _('Post an announcement for this classroom...'))
        .row
          .twelve.columns
            = submit_tag(_('Publish'), :class => 'button small primary', :id => :submit_announcement)

    = render(:partial => 'shared/timeline')

  = render(:partial => 'sidebar')

app/views/coursewareable/classrooms/edit.html.haml
= title _('Customize %s') % @classroom.title
= head_embed javascript_include_tag('editor')
= head_embed stylesheet_link_tag('editor')

#classroom
  .eight.columns

    = render('shared/classroom_customization_tabs')

    = form_for(@classroom, :url => classroom_path) do |f|
      .row
        .two.columns
          = f.label :title, _('Title'), :class => 'right inline'
        .ten.columns
          = f.text_field :title, :required => true

      .row
        .two.columns
          = f.label :slug, _('Sub-domain'), :class => 'right inline'
        .ten.columns
          .row.collapse
            .eight.columns
              = f.text_field :slug, :placeholder => _('Leave empty to be generated, minimum length 4, maximum 32.')
            .four.columns
              %span.postfix
                = ".#{Courseware.config.domain_name}"

      .row
        .two.columns
          = f.label :description, _('Description'), :class => 'right inline'
        .ten.columns
          = f.text_area :description, :class => 'wysiwyg-minimal', :required => true

      .row
        .two.columns
          = f.label :header_image, _('New header'), :class => 'right inline'
        .ten.columns
          = f.file_field :header_image
          %em.smaller
            = _('Should be at least %{width}px wide and %{height}px high.') % Courseware.config.header_image_size

      .row
        .ten.offset-by-two.columns
          = f.submit _('Update'), :id => 'edit_classroom', :class => 'button primary'

  = render(:partial => 'edit_sidebar')

app/views/coursewareable/classrooms/new.html.haml
= title _('Start a new classroom')

#classroom
  .eight.columns.centered.end

    = form_for(@new_classroom, :url => start_classroom_path) do |f|

      .row
        .three.columns
          = f.label :title, _('Name it'), :class => [:right, :inline]
        .eight.columns.end
          = f.text_field :title, :required => true

      .row
        .three.columns
          = f.label :description, _('Short description'), :class => [:right, :inline]
        .eight.columns.end
          = f.text_area :description, :rows => 3, :required => true

      .actions
        .row
          .nine.columns.offset-by-three
            = f.submit _('Start now!'), :id => 'submit_new_classroom', :class => 'button primary'

app/views/coursewareable/classrooms/staff.html.haml
= title  _('%s classroom personnel') % @classroom.title

#classroom-staff
  .eight.columns

    %h4
      = _('Initiator')
    %hr

    .row
      .two.columns.author.avatar.align-right
        = gravatar_image_tag(@classroom.owner.email, :alt => @classroom.owner.name, :gravatar => {:size => 50})
      .ten.columns
        %h5
          = @classroom.owner.name
        %p.smaller
          = _('Started the classroom on %s') % @classroom.created_at.to_s(:pretty)
        - unless @classroom.owner.description.blank?
          %p
            = @classroom.owner.description.html_safe

    - if @classroom.collaborations_count > 0
      %h4
        = _('Collaborators')
      %hr

      - @classroom.collaborations.each do |collab|
        .row
          .two.columns.author.avatar.align-right
            = gravatar_image_tag(collab.user.email, :alt => collab.user.name, :gravatar => {:size => 50})
          .ten.columns
            %h5
              = collab.user.name
            %p.smaller
              = _('Since %s') % collab.created_at.to_s(:pretty)
            - unless collab.user.description.blank?
              %p
                = collab.user.description.html_safe

            %hr

  = render(:partial => 'sidebar')

app/views/coursewareable/classrooms/stats.html.haml
= title  _('%s classroom stats') % @classroom.title
= head_embed javascript_include_tag('punchcard')

#classroom-stats
  .eight.columns

    %h4
      = _('Activities punchcard')
    %hr

    .row
      .twelve.columns

        .punchcard

  = render(:partial => 'sidebar')